version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appletech-app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html:cached
      - ./src/docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "8000:80"
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appletech-queue
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html:cached
      - ./src/docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    command: php artisan queue:work --tries=3 --timeout=90

  db:
    image: postgres:15
    container_name: appletech-db
    restart: always
    environment:
      POSTGRES_DB: appletech
      POSTGRES_USER: appletech_user
      POSTGRES_PASSWORD: APPLETECH2026
    volumes:
      - appletech-laravel_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # puerto cambiado para evitar choques

  node:
    image: node:18
    container_name: appletech-node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    command: sh -c "npm install && npm run build"

  adminer:
    image: adminer
    container_name: appletech-adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  appletech-laravel_db_data:
